In [1]:
import torch

In [4]:
randint = torch.randint(-100,100, (6,))
randint

tensor([ 27,  27,  86,  -8, -80,  59])

In [6]:
tensor = torch.tensor([[1.1,2.9], [2.3, 2.5], [0.9,1.2]])
tensor

tensor([[1.1000, 2.9000],
        [2.3000, 2.5000],
        [0.9000, 1.2000]])

In [8]:
zeros = torch.zeros(3,9)
zeros

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
linspace = torch.linspace(3,10, steps=15)
linspace

tensor([ 3.0000,  3.5000,  4.0000,  4.5000,  5.0000,  5.5000,  6.0000,  6.5000,
         7.0000,  7.5000,  8.0000,  8.5000,  9.0000,  9.5000, 10.0000])

In [13]:
eye = torch.eye(3)
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [18]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])