In [1]:
import torch

In [4]:
randint = torch.randint(-100,100, (6,))
randint

tensor([ 27,  27,  86,  -8, -80,  59])

In [6]:
tensor = torch.tensor([[1.1,2.9], [2.3, 2.5], [0.9,1.2]])
tensor

tensor([[1.1000, 2.9000],
        [2.3000, 2.5000],
        [0.9000, 1.2000]])

In [8]:
zeros = torch.zeros(3,9)
zeros

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
linspace = torch.linspace(3,10, steps=15)
linspace

tensor([ 3.0000,  3.5000,  4.0000,  4.5000,  5.0000,  5.5000,  6.0000,  6.5000,
         7.0000,  7.5000,  8.0000,  8.5000,  9.0000,  9.5000, 10.0000])

In [13]:
eye = torch.eye(3)
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [18]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [2]:
# Example to test Performance difference between CPU & GPU

import torch
import numpy as np
import time
device = 'mps' if torch.backends.mps.is_available() else 'cpu' # using 'mps' instead of 'cuda' for MacOS
print(device)

mps


In [3]:
# Example of a 2D Matrix Operation
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)
np_rand1 = torch.rand(10000, 10000)
np_rand2 = torch.rand(10000, 10000)

start_time = time.time()
rand = (torch_rand1 @ torch_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"GPU Time for 2D matrix operation:{elapsed_time:.8f}secs")

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"CPU Time for 2D matrix operation:{elapsed_time:.8f}secs")


GPU Time for 2D matrix operation:0.24378610secs
CPU Time for 2D matrix operation:0.56297517secs


In [4]:
# Example of a 4D Matrix Operation.
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()
rand = (torch_rand1 @ torch_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"GPU Time for 4D matrix operation:{elapsed_time:.8f}secs")

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"CPU Time for 4D matrix operation:{elapsed_time:.8f}secs")


GPU Time for 4D matrix operation:0.06150198secs
CPU Time for 4D matrix operation:0.07427883secs
